<?php 
/*
 * Newly two variable is post 
 * $product_uri, $image_uri
 * */

if(isset($_POST['seller']) && isset($_POST['buyer_email']) && isset($_POST['subject']) && isset($_POST['p_name']) && isset($_POST['p_sku']) && isset($_POST['message']))
:?>




<html xmlns="http://www.w3.org/1999/xhtml"><head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>Buyer Request</title>
</head>

<body yahoo="" bgcolor="#ffffff" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;min-width:100%!important;" >
<table width="100%" bgcolor="#ffffff" border="0" cellpadding="10" cellspacing="0" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse !important;" >
<tbody><tr>
  <td style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;" >
    <!--[if (gte mso 9)|(IE)]>
      <table width="600" align="center" cellpadding="0" cellspacing="0" border="0" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse !important;" >
        <tr>
          <td style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;" >
    <![endif]-->
    <table bgcolor="#ffffff" class="content" align="center" cellpadding="0" cellspacing="0" border="0" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse !important;width:100%;max-width:600px;" >
			<tbody>
				
			<tr>
				<td valign="top" mc:edit="headerBrand" id="templateContainerHeader" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;font-size:14px;padding-top:2.429em;padding-bottom:0.929em;" >

					<p style="text-align:center;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;color:#545454;display:block;font-family:Helvetica;font-size:14px;line-height:1.500em;font-style:normal;font-weight:normal;letter-spacing:normal;" >
						<img src="http://sindhbad.com/images/logo.png" style="max-width:600px;display:inline-block;-ms-interpolation-mode:bicubic;border-width:0;line-height:100%;outline-style:none;text-decoration:none;height:auto;min-height:1px;" >
					</p>

				</td>
			</tr>
			<tr>
				<td align="center" valign="top" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;" >
						<!-- BEGIN BODY // -->
							<table border="0" cellpadding="0" cellspacing="0" width="100%" id="templateContainer" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse !important;border-top-width:1px;border-top-style:solid;border-top-color:#e2e2e2;border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:#e2e2e2;border-left-width:1px;border-left-style:solid;border-left-color:#e2e2e2;border-right-width:1px;border-right-style:solid;border-right-color:#e2e2e2;border-radius:4px 4px 4px 4px;background-clip:padding-box;border-spacing:0;" >
									<tbody><tr>
											<td valign="top" class="bodyContent" mc:edit="body_content" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;color:#505050;font-family:Helvetica;font-size:14px;line-height:150%;padding-top:3.143em;padding-right:3.5em;padding-left:3.5em;padding-bottom:0.714em;text-align:left;" >
												<p style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;color:#545454;display:block;font-family:Helvetica;font-size:14px;line-height:1.500em;font-style:normal;font-weight:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:15px;margin-left:0;text-align:left;" >Dear <?= $_POST['seller'] ?? ''; ?> you have received message from buyer.</p>
												<p style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;color:#545454;display:block;font-family:Helvetica;font-size:14px;line-height:1.500em;font-style:normal;font-weight:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:15px;margin-left:0;text-align:left;" >
													Buyer Email Address: <?= $_POST['buyer_email'] ?? '';?></p>
													
													
												<p style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;color:#545454;display:block;font-family:Helvetica;font-size:14px;line-height:1.500em;font-style:normal;font-weight:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:15px;margin-left:0;text-align:left;" >	Subject	: <?= $_POST['subject'] ?? ''; ?></p>
												<p style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;color:#545454;display:block;font-family:Helvetica;font-size:14px;line-height:1.500em;font-style:normal;font-weight:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:15px;margin-left:0;text-align:left;" >	Product Name	: <?= $_POST['p_name'] ?? ''; ?></p>
												
												<p style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;color:#545454;display:block;font-family:Helvetica;font-size:14px;line-height:1.500em;font-style:normal;font-weight:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:15px;margin-left:0;text-align:left;" >	Product SKU	: <?= $_POST['p_sku'] ?? ''; ?></p>
												<p style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;color:#545454;display:block;font-family:Helvetica;font-size:14px;line-height:1.500em;font-style:normal;font-weight:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:15px;margin-left:0;text-align:left;" > Message: <?= $_POST['message'] ?? ''; ?></p>
												<p style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;color:#545454;display:block;font-family:Helvetica;font-size:14px;line-height:1.500em;font-style:normal;font-weight:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-bottom:15px;margin-left:0;text-align:left;" > Product Link: <a href = "<?= $_POST['product_uri'] ?? ''; ?>">Click Here</a></p>

											
											</td>
											
											<td valign="top"  >
												<span >
													<img style = "max-width:350px; width:100%; max-height:350px; height:100%;" src = "<?= $_POST['image_uri'] ?? '';?>" />
												</span>
											</td>
									
									</tr>

									<tr align="top">
											<td valign="top" class="bodyContentImage" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;color:#505050;font-family:Helvetica;font-size:14px;line-height:150%;padding-top:0;padding-right:3.571em;padding-left:3.571em;padding-bottom:2em;text-align:left;" >
												<table border="0" cellpadding="0" cellspacing="0" valign="top" style="-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse !important;" >
													<tbody><tr>
														<td align="left" width="50" valign="top" mc:edit="footer_sigimage" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;" >
															<p style="margin-bottom:10px;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;display:block;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;color:#545454;font-family:Helvetica;font-size:14px;line-height:1.500em;font-style:normal;font-weight:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-left:0;text-align:left;" >
																<img src="" style="max-width:600px;display:block;-ms-interpolation-mode:bicubic;border-width:0;line-height:100%;outline-style:none;text-decoration:none;height:auto;min-height:1px;" >
															</p>
														</td>
														<td width="15" align="left" valign="top" style="width:15px;margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:0;padding-bottom:0;padding-right:0;padding-left:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;" >&nbsp;</td>
														<td align="left" valign="top" mc:edit="footer_sig" style="margin-top:0;margin-bottom:0;margin-right:0;margin-left:0;padding-top:10px;line-height:1;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;mso-table-lspace:0pt;mso-table-rspace:0pt;" >
															<h4 style="display:block;font-family:Helvetica;font-style:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-left:0;text-align:left;color:#4E4E4E;font-size:13px;line-height:1.154em;font-weight:normal;margin-bottom:0;" ><strong>Customer Service Executive</strong></h4>
															<h5 style="display:block;font-family:Helvetica;font-style:normal;font-weight:normal;letter-spacing:normal;margin-top:0;margin-right:0;margin-left:0;text-align:left;color:#828282;font-size:12px;line-height:1.667em;margin-bottom:0;" >Sindhbad LLC</h5>
														</td>
													</tr>
												</tbody></table>
											</td>
									</tr>
							
							
							
							
							
							
							</tbody></table>
							<!-- // END BODY -->
					</td>
			</tr>
			
    </tbody></table>
    <!--[if (gte mso 9)|(IE)]>
          </td>
        </tr>
    </table>
    <![endif]-->
    </td>
  </tr>
</tbody></table>


</body></html>

<?php endif; ?>
