<?php

require('controller/controller.php');

// Setting time to dubai
date_default_timezone_set ('Asia/Dubai');
// Get the object
$obj = new MarketPlace();


?>

<!doctype html>
<html lang="en">
   
	<head >
     
      <meta charset="utf-8"/>
      <meta name="description" content="Default Description"/>
      <meta name="keywords" />
      <meta name="robots" content="INDEX,FOLLOW"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <meta name="format-detection" content="telephone=no"/>
      <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
      <title>Home - SM Market Layout 4</title> 
      <?php include 'head-links.php'; ?>
      <!--CUSTOM CSS-->
     
      
	   <style>
      

      input[type="checkbox"] {


          top: 1px;
          left: 0;
          content: '';
          display: inline-block;
          width: 16px; 
          height: 16px; 
          border: 1px solid #e3e1e1;
          background-color: #f7f7f7;
          border-radius: 3px;
          -webkit-border-radius: 3px;
          z-index: 5;
      } 


    .items div a {
    position: relative;
    padding-left: 4px;
    bottom: 4px;
}


 .items div {
    margin-bottom: 10px;
}


.items div a:before {
    position: absolute;
    top: 1px;
    left: 0;
    content: '';
    display: inline-block;
   
    border: 1px solid #e3e1e1;
    background-color: #f7f7f7;
    border-radius: 3px;
    -webkit-border-radius: 3px;
    z-index: 5;

}


 .items div a .count {
    float: right;
    margin-left: 5px;
}

     </style>
	   <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	
	   
     </head>
  





	 <body data-container="body">
      
      
     
      
      
      
      
      <noscript>
         <div class="message global noscript">
            <div class="content">
               <p><strong>JavaScript seems to be disabled in your browser.</strong> <span>For the best experience on our site, be sure to turn on Javascript in your browser.</span></p>
            </div>
         </div>
      </noscript>
      
      
     
      
      <div class="page-wrapper">
      
       <?php include 'header.php'; ?>
			
		<main id="maincontent" class="page-main">
		<div class="columns col1-layout">
               <div class="container">
                  <div class="row">
                     <div class="col-lg-12 col-md-12"> 
                     
                     <div class="col-lg-3 col-md-3 order-1 col-left-sidebar">
   <div class="sidebar sidebar-main">
      <div class="block filter">
         <div class="block-title filter-title"><strong>Filter Result </strong></div>
         <div class="block-content filter-content">
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle">Shopping Options</strong> 
            <dl class="filter-options" id="narrow-by-list">
               <dt role="heading" aria-level="3" class="filter-options-title">Brand</dt>
               <dd class="filter-options-content">
                  <ol class="items">

                    <div class = "category-list-10">
                      
                      <input type = "checkbox" value = "samsung" name = "brand[]" id = "brand1"> 

                     <a >

                      Samsung  <span class="count">7<span class="filter-count-label"> items</span></span> </a>
                  
                    <div class = "category-list-10">
                      
                      <input type = "checkbox" value = "htc" name = "brand[]" id = "brand4"> 

                     <a >

                      HTC  <span class="count">7<span class="filter-count-label" id = "brand3"> items</span></span> </a>          
                  

                  <div class = "category-list-10">
                      
                      <input type = "checkbox" value = "apple" name = "brand[]" id = "brand2"> 

                     <a >

                      Apple  <span class="count">7<span class="filter-count-label"> items</span></span> </a>          
                  
                    </div>
            

                  </ol>


              <dt role="heading" aria-level="3" class="filter-options-title">Operating System</dt>
               <dd class="filter-options-content">
                  <ol class="items">

                    <div class = "category-list-10">
                      
                      <input type = "checkbox" value = "linux" name = "os[]" id = "os1"> 

                     <a >

                      Linux <span class="count">7<span class="filter-count-label"> items</span></span> </a>
                  
                    <div class = "category-list-10">
                      
                      <input type = "checkbox" value = "windows" name = "os[]" id = "os2"> 

                     <a >

                      Windows <span class="count">7<span class="filter-count-label"> items</span></span> </a>          
                  
                  <div class = "category-list-10">
                      
                      <input type = "checkbox" value = "macos" name = "os[]" id = "os3"> 

                     <a >

                      Mac OSX<span class="count">7<span class="filter-count-label"> items</span></span> </a>          
                  
                    </div>
            

                  </ol>

               


               </dd>
               




               </dd>


               </dd>
               

               <dt role="heading" aria-level="3" class="filter-options-title">Manufacturer</dt>
               


               <dt role="heading" aria-level="3" class="filter-options-title">Material</dt>
               

               <dt role="heading" aria-level="3" class="filter-options-title">Price</dt>
               

               




               </dd>
           


            </dl>
         </div>
      </div>
   </div>



   <div class="sidebar sidebar-additional">
      <div class="block block-compare" data-bind="scope: 'compareProducts'" data-role="compare-products-sidebar">
         <div class="block-title"><strong id="block-compare-heading" role="heading" aria-level="2">Compare Products</strong> <span class="counter qty no-display" data-bind="text: compareProducts().countCaption, css: {'no-display': !compareProducts().count}"></span></div>
         <!-- ko if: compareProducts().count --><!-- /ko --><!-- ko ifnot: compareProducts().count -->
         <div class="empty">You have no items to compare.</div>
         <!-- /ko -->
      </div>
      <div id="sm_filterproducts_15476770811323539721" class="block products-sidebar">
         <div class="block-title filter-title"><strong>Featured Product</strong></div>
         <div class="block-content block-content-products">
            <div class="item product product-item">
               <div class="item-inner clearfix">
                  <div class="box-image"><a href="http://localhost/themes/sm_market2/default/wireless-bluetooth-speaker-sony-x3.html" class="product photo product-item-photo" tabindex="-1">  <span class="product-image-container"><span class="product-image-wrapper"><img class="product-image-photo lazyload" src="http://localhost/themes/sm_market2/pub/media/lazyloading/blank.png" data-src="http://localhost/themes/sm_market2/pub/media/catalog/product/cache/c5b0e6136a6dd7f7d91d8b889ed40f35/f/u/fuhlen_mouse_for_gamer_1.jpg" width="" height="" alt="Fuhlen Mouse for Gamer"></span></span></a></div>
                  <div class="product details product-item-details box-info">
                     <strong class="product name product-name product-item-name"><a class="product-item-link" href="http://localhost/themes/sm_market2/default/wireless-bluetooth-speaker-sony-x3.html">Fuhlen Mouse for Gamer</a></strong>    
                     <div class="product-reviews-summary short">
                        <div class="rating-summary">
                           <span class="label"><span>Rating:</span></span> 
                           <div class="rating-result" title="87%"><span style="width:87%"><span>87%</span></span></div>
                        </div>
                        <div class="reviews-actions"><a class="action view" href="http://localhost/themes/sm_market2/default/wireless-bluetooth-speaker-sony-x3.html#reviews">1&nbsp;<span>Review</span></a></div>
                     </div>
                     <div class="price-box price-final_price" data-role="priceBox" data-product-id="2281" data-price-box="product-id-2281">     <span class="price-container price-final_price tax weee"> <span id="product-price-2281" data-price-amount="250" data-price-type="finalPrice" class="price-wrapper "><span class="price">$250.00</span></span>  </span>  </div>
                  </div>
               </div>
            </div>



            <div class="item product product-item">
               <div class="item-inner clearfix">
                  <div class="box-image"><a href="http://localhost/themes/sm_market2/default/acer-all-in-one-computers.html" class="product photo product-item-photo" tabindex="-1">  <span class="product-image-container"><span class="product-image-wrapper"><img class="product-image-photo lazyload" src="http://localhost/themes/sm_market2/pub/media/lazyloading/blank.png" data-src="http://localhost/themes/sm_market2/pub/media/catalog/product/cache/c5b0e6136a6dd7f7d91d8b889ed40f35/a/c/acer_aspire_s24_all-in-one_pc_2.jpg" width="" height="" alt="Acer Aspire S24 All In One PC"></span></span></a></div>
                  <div class="product details product-item-details box-info">
                     <strong class="product name product-name product-item-name"><a class="product-item-link" href="http://localhost/themes/sm_market2/default/acer-all-in-one-computers.html">Acer Aspire S24 All In One PC</a></strong>    
                     <div class="product-reviews-summary short">
                        <div class="rating-summary">
                           <span class="label"><span>Rating:</span></span> 
                           <div class="rating-result" title="87%"><span style="width:87%"><span>87%</span></span></div>
                        </div>
                        <div class="reviews-actions"><a class="action view" href="http://localhost/themes/sm_market2/default/acer-all-in-one-computers.html#reviews">1&nbsp;<span>Review</span></a></div>
                     </div>
                     <div class="price-box price-final_price" data-role="priceBox" data-product-id="2280" data-price-box="product-id-2280">   <span class="special-price">  <span class="price-container price-final_price tax weee"> <span class="price-label">Special Price</span>  <span id="product-price-2280" data-price-amount="400" data-price-type="finalPrice" class="price-wrapper "><span class="price">$400.00</span></span>  </span></span> <span class="old-price">  <span class="price-container price-final_price tax weee"> <span class="price-label">Regular Price</span>  <span id="old-price-2280" data-price-amount="450" data-price-type="oldPrice" class="price-wrapper "><span class="price">$450.00</span></span>  </span></span>  </div>
                  </div>
               </div>
            </div>



            <div class="item product product-item">
               <div class="item-inner clearfix">
                  <div class="box-image"><a href="http://localhost/themes/sm_market2/default/washing-machines-dryers.html" class="product photo product-item-photo" tabindex="-1">  <span class="product-image-container"><span class="product-image-wrapper"><img class="product-image-photo lazyload" src="http://localhost/themes/sm_market2/pub/media/lazyloading/blank.png" data-src="http://localhost/themes/sm_market2/pub/media/catalog/product/cache/c5b0e6136a6dd7f7d91d8b889ed40f35/w/a/washing_machines_elextrolux.jpg" width="" height="" alt="Washing Machines Elextrolux"></span></span></a></div>
                  <div class="product details product-item-details box-info">
                     <strong class="product name product-name product-item-name"><a class="product-item-link" href="http://localhost/themes/sm_market2/default/washing-machines-dryers.html">Washing Machines Elextrolux</a></strong>    
                     <div class="product-reviews-summary short">
                        <div class="rating-summary">
                           <span class="label"><span>Rating:</span></span> 
                           <div class="rating-result" title="80%"><span style="width:80%"><span>80%</span></span></div>
                        </div>
                        <div class="reviews-actions"><a class="action view" href="http://localhost/themes/sm_market2/default/washing-machines-dryers.html#reviews">1&nbsp;<span>Review</span></a></div>
                     </div>
                     <div class="price-box price-final_price" data-role="priceBox" data-product-id="2279" data-price-box="product-id-2279">     <span class="price-container price-final_price tax weee"> <span id="product-price-2279" data-price-amount="185" data-price-type="finalPrice" class="price-wrapper "><span class="price">$185.00</span></span>  </span>  </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <script type="text/javascript">
         require([
             'jquery'
         ], function ($) {
             var $element = $('#sm_filterproducts_15476770811323539721');
         
             function CountDown(date, id) {
                 dateNow = new Date();
                 amount = date.getTime() - dateNow.getTime();
                 delete dateNow;
                 if (amount < 0) {
                     id.html("Now!");
                 } else {
                     days = 0;
                     hours = 0;
                     mins = 0;
                     secs = 0;
                     out = "";
                     amount = Math.floor(amount / 1000);
                     days = Math.floor(amount / 86400);
                     amount = amount % 86400;
                     hours = Math.floor(amount / 3600);
                     amount = amount % 3600;
                     mins = Math.floor(amount / 60);
                     amount = amount % 60;
                     secs = Math.floor(amount);
                     $(".time-day .num-time", id).text(days);
                     $(".time-day .title-time", id).text(((days <= 1) ? "Day" : "Days"));
                     $(".time-hours .num-time", id).text(hours);
                     $(".time-hours .title-time", id).text(((hours <= 1) ? "Hour" : "Hours"));
                     $(".time-mins .num-time", id).text(mins);
                     $(".time-mins .title-time", id).text(((mins <= 1) ? "Min" : "Mins"));
                     $(".time-secs .num-time", id).text(secs);
                     $(".time-secs .title-time", id).text(((secs <= 1) ? "Sec" : "Secs"));
                     setTimeout(function () {
                         CountDown(date, id)
                     }, 1000);
                 }
             }
         
             $(".deals-countdown", $element).each(function () {
                 var timer = $(this).data('timer');
                 var data = new Date(timer);
                 CountDown(data, $(this));
             });
         });
      </script>  
   </div>
</div>
                     
                    </div>
                    </div>
                </div>
          </div>
		
		</main>
         
         
         <?php 
			
			include ('footer.php');
         ?>
      </div>
      
      <script src = "js/urlCRUD.js" ></script>
    <script type = "text/javascript">

//localStorage.clear();

    // Get the local storage checked checkbox ides 
    var getCheckboxesids = JSON.parse(localStorage.getItem("checkboxsids"));
    for(var i in getCheckboxesids) {


    if(getCheckboxesids[i] == true) {

    $('#'+i).prop('checked', true);
    }


    }

    var checkboxids = {};


    $("input:checkbox").each(function(elements) {

    // Get attribute id 
    let id = $(this).attr('id');

    checkboxids[id] = false;

    });

    // Convert object to json 
    if (typeof(Storage) !== "undefined") {
    // Code for localStorage/sessionStorage.

    if (localStorage.getItem("checkboxsids") === null) {
    //...
    localStorage.setItem('checkboxsids', JSON.stringify(checkboxids));
    }
    } 

    var checkboxids = [];

    // Current url 
    var CURL = window.location;

    $('#narrow-by-list input[type="checkbox"]').change(function (){

     // Checkbox is checked 
    var name = $(this).attr('name')

    // var 
    var elValue = $(this).val();

    // If checked 
    name = name.slice(0, -2); 

    // Qeury string 
    var stringToQuery = '';

    // Switch 
    switch (name) {

        case 'os':
        stringToQuery= 'os';
        break;

        case 'brand':
        stringToQuery= 'brand';
        break;

        default:
        break;

    }

    // Get the querystring name al
    var getQueryString = getParameterByName(stringToQuery);

    // Get the id of the current elemnt 
    var id = $(this).attr('id');

    // Get checkboxes id from localstorate 
    var checkboxs = JSON.parse(localStorage.getItem("checkboxsids"));

    // If chancked happend 
    if(this.checked === true) {
        
        // IF query string is not null and its present such as ?brand=something 
        if(getQueryString !== null) {

          // Set checkbox ids to true 
          checkboxs[id] = true;

          // Update locastorage item with it's updated value 
          localStorage.setItem('checkboxsids', JSON.stringify(checkboxs));

            // If value is not present is query string such as ?brand = apple,samsung and apple 
            if(getQueryString.indexOf(elValue) === -1){


                // Then append the query string value to the string apple,samsung 
               getQueryString += ','+elValue;
          
            }         

        // If query string do not exist for exp ?brand=samsung while appending samsung 
        } else {

            // Enable checkbox id 
            checkboxs[id] = true;

            // Update local storage value 
            localStorage.setItem('checkboxsids', JSON.stringify(checkboxs));

            // Return new location of the windows 
            return window.location.search = updateQueryStringParameter(window.location.search, name, encodeURI(elValue));

        }

      // If element unchacked then 
    } else {

    // Check if there is many query string such as brand=apple,samsung or brand=apple only 
    if(getQueryString.indexOf(',') !== -1) {

    // Split query string value [apple, brand ]
    var sqs = getQueryString.split(',');

    // Remove the value from array 
    sqs.remove(elValue);

    // Set new string value of removed element from the array 
    getQueryString = sqs.join(',');

    // If there is only ?brand=samsung 
    } else {
    	
    	// Checkbox id to false 
    	checkboxs[id] = false;

      // Update local storage 
    	localStorage.setItem('checkboxsids', JSON.stringify(checkboxs));
    	
      // Set windows new location 
    	return window.location.href = removeQueryStringParameter(window.location.href, stringToQuery);
    	
    	

    }


    checkboxs[id] = false;

    localStorage.setItem('checkboxsids', JSON.stringify(checkboxs));

    return window.location.search = updateQueryStringParameter(window.location.search, name, encodeURI(getQueryString));

    }


      window.location.search = updateQueryStringParameter(window.location.search, name, encodeURI(getQueryString));

  })

    </script>
       
      
      </body>
     </html>

	
