<?php require_once('controller/controller.php');

if(!isset($obj)) {
	$obj = new MarketPlace();
} 


?>
<div class="minicart-header">
								<div class="minicart-content">
								<div class="cart-wrapper">
									<div data-block="minicart" class="minicart-wrapper">
									<div class="minicart-content">
									
									<div class="cart-wrapper">
										<div data-block="minicart" class="minicart-wrapper active">
                     <a class="action showcart active" data-bind="scope: 'minicart_content'" id = "min-cart-triger">
                        <span class="text"><span class="df-text">Shopping Cart</span><span class="hidden">

                          <?php $translate->__('My Cart - '); ?></span></span> 
                        <span class="counter qty">
                           <span class="counter-number"></span> 
                           <span class="counter-label">
							   
							  
							   <?= $obj->CartTotleQty() == null ? '0' : $obj->CartTotleQty(); ?>
							   
							   <?php if($obj->CartTotleQty() > 1 ) :?>
							   <span>
                
                 <?= $translate->__('items'); ?> 

               </span>
							   
							   <?php else: ?>
							   <span><?= $translate->__('item'); ?> </span>
							   
							   <?php endif; ?>
								   
								   
							   
                              
                           </span>
                           <span class="price-minicart">
                             
                              <div class="subtotal">
                                 <span class="label">
                                    <span>Cart Subtotal</span>
                                 </span>
                                
                                 <div class="amount price-container">
                                    
                                    <span class="price-wrapper" data-bind="html: cart().subtotal_excl_tax"><span class="price">$200.00</span></span>
                                   
                                 </div>
                                 
                              </div>
                              
                           </span>
                        </span>
                     </a>
                     
                     
                     <div class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-front mage-dropdown-dialog" tabindex="-1" role="dialog" aria-describedby="ui-id-3" style="display: block;">
                        
                        <!--- IF there is antyting in cart then with element will be shown--->
                        <?php if( $obj->GetCart() !== NULL && count($obj->GetCart() > 0)) :?>
                        
                        
                        <div style = "display:none; margin-top:20px;" class="block block-minicart empty ui-dialog-content ui-widget-content" data-role="dropdownDialog" id="mincart-id-253" >
                           
                           <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                              
                              <div class="block-title">
                                 <strong>
                                    <span class="text">
                                       <span>My Cart</span>
                                    </span>
                                    <span class="qty">
                                       <?= $obj->CartTotleQty() == null ? '0' : $obj->CartTotleQty(); ?>
                                    </span>
                                 </strong>
                              </div>
                              <div class="block-content" >
                                 <button type="button" id="btn-minicart-close" class="action close" data-action="close" data-bind="attr: { title: $t('Close') }" title="Close">
                                    <span>
                                       <span>Close</span>
                                    </span>
                                 </button>
                                 
                                 <div class="items-total">
                                    <span class="count">
                                      <?= $obj->CartTotleQty() == null ? '0' : $obj->CartTotleQty(); ?>
                                    </span>
                                    
                                    <span>item</span>
                                    
                                 </div>
                                 <div class="header-minicart">
                                    <span class="text-left">
                                       <span>Your Product</span>
                                    </span>
                                    <span class="text-right">
                                      <span>Price</span>
                                    </span>
                                 </div>
                                 
                                 <strong class="subtitle">
                                    <span>Recently added item()</span>
                                 </strong>
                                 <div data-action="scroll" class="minicart-items-wrapper" style="height: 140px;">
                                    <ol id="mini-cart" class="minicart-items">
                                         
                                         <?php foreach($obj->GetCart() as $item) :?>
                                         
                                         <li class="item product product-item odd last" data-role="product-item">
                                          
                                          
                                          
                                          <div class="product">
                                             <a  tabindex="-1" class="product-item-photo" href="http://localhost/themes/sm_market2/travel-crossbody-shoulder-bag.html" title="Zara Women Leather Bag">
                                                <span class="product-image-container"  style="width: 80px;">
                                                <span class="product-image-wrapper"  style="padding-bottom: 100%;">
                                               
                                               
                                               
                                                <img class="product-image-photo"  src= "<?= $item['image'];?>" alt="Zara Women Leather Bag" style="width: 40px; height: 40px;">
                                               
                                               
                                               
                                               
                                                </span>
                                                </span>
                                                
                                                
                                             </a>
											
											
                                             <div class="product-item-details">
                                                <strong class="product-item-name">
                                                  
                                                   <a href=""><?= substr($item['name'], 0, 15)?>...</a>

                                                </strong>
                                               
                                                <div class="product-item-pricing">
                                                   
                                                   <div class="price-container">
                                                      <span class="price-wrapper" data-bind="html: price">   <span class="price-excluding-tax" data-label="Excl. Tax"> <span class="minicart-price"> <span class="price">
														  
														  <?= $obj->getPriceFormate($item['totalamount'])?>  AED </span></span> </span>  </span>
                                                   </div>

                                                   <div class="details-qty qty">
                                                      <label class="label">Qty</label>
                                                      
                                                      
                                                      
                                                      <input type="number" size="4" class="item-qty cart-item-qty" id="cart-item-1514-qty" value = "<?= $item['qty']?>" disabled>

                                                      <button style="display: none" id="update-cart-item-1514" data-cart-item="1514" title="Update">
                                                      
                                                      <span data-bind="i18n: 'Update'">Update</span>
                                                      
                                                      </button>
                                                  
                                                  
                                                  
                                                  
                                                   </div>
                                                </div>
                                                <div class="product actions">
                                                  
                                                   <div class="primary">
                                                      <a data-bind="attr: {href: configure_url, title: $t('Edit item')}" class="action edit" href="http://localhost/themes/sm_market2/checkout/cart/configure/id/1514/product_id/2244/" title="Edit item">
                                                      <span data-bind="i18n: 'Edit'">Edit</span>
                                                      </a>
                                                   </div>
                                                   
                                                   <!--
                                                   <div class="secondary">
                                                      <a href="#" data-bind="attr: {'data-cart-item': item_id, title: $t('Remove item')}" class="action delete" data-cart-item="1514" title="Remove item">
                                                      <span data-bind="i18n: 'Remove'">Remove</span>
                                                      </a>
                                                   </div>
                                                
                                                -->
                                                
                                                </div>
                                             </div>
                                         
											
                                         
                                         
                                         
                                          </div>
                                       </li>
                                      
                                      
                                       <?php endforeach; ?>
                                       
                                    </ol>
                                 </div>
                                
                                 <div class="subtotal">
                                    <span class="label">
                                       <span>Cart Subtotal</span>
                                    </span>
                                   
                                    <div class="amount price-container">
                                       
                                       <span class="price-wrapper"><span class="price">
										
                                       </span><?= $obj->getPriceFormate($obj->CartTotleAmountWithTax());?> AED</span>
                                      
                                    </div>
                                    
                                    
                                 </div>
                                 <div class="actions">
                                    <a class="action viewcart" href="/cart">
                                       <span>
                                        <span>View cart</span>
                                       </span>
                                    </a>
                                    <a href = "/checkout" id="top-cart-btn-checkout" type="button" class="action checkout"  title="Go to Checkout">
                                       <span>Checkout</span>
                                    </a>
                                    <div ></div>
                                 </div>
                                 
                                 <div id="minicart-widgets" class="minicart-widgets">

                                 </div>
                              </div>
                            
                              
                           </div>
                        
                        </div>
						
						<!--- End of IF there is antyting in cart then with element will be shown--->
						
						<?php else: ?>
						<!--- If there is no cart then this message will be shown --->
						<div class="block block-minicart empty ui-dialog-content ui-widget-content" data-role="dropdownDialog" id="mincart-id-253" style="display: none; margin-top:20px;"><div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
						<div class="block-title">
						<strong>
        <span class="text"><span>My Cart</span></span>
        <span class="qty empty">
			0
        </span>
    </strong>
						</div>

						<div class="block-content">
    <button type="button" id="btn-minicart-close" class="action close" data-action="close" data-bind="attr: { title: $t('Close') }" title="Close">
        <span><!-- ko i18n: 'Close' --><span>Close</span></span>
    </button>

     <strong class="subtitle empty" data-bind="visible: closeSidebar()">
            <span>You have no items in your shopping cart.</span>
        </strong>
    

    <div id="minicart-widgets" class="minicart-widgets">

    </div>
</div>
						</div></div>
						
						<!---  End of If there is no cart then this message will be shown --->
						<?php endif; ?>
						
						
                     
                     </div>
                 
                 
                 
                 
                  </div>
									</div>
            
            
            
            
            
            
            </div>
						<div class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-front mage-dropdown-dialog" tabindex="-1" role="dialog" aria-describedby="ui-id-3" style="display: none;">
               <div class="block block-minicart empty ui-dialog-content ui-widget-content" data-role="dropdownDialog" id="ui-id-3" style="display: block;">
                  <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                  </div>
               </div>
            </div>
						</div>
						</div>
						</div>
						</div>
                       
