web:
    image: nginx:latest
    volumes:
        - ./code:/code
        - ./default.conf:/etc/nginx/conf.d/default.conf
        
    links:
        - php
php:
    volumes:
        - ./code:/code
    build: ./php
db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: a
       MYSQL_DATABASE: iptikar-marketplace
       MYSQL_USER: root
       MYSQL_PASSWORD: a
phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - db:db
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: a
    MYSQL_PORT_3306_TCP_ADDR: db
    

