web:
    image: nginx:latest
    volumes:
        - ./code:/code
        - ./default.conf:/etc/nginx/conf.d/default.conf
        
    links:
        - php
php:
    volumes:
        - ./code:/code
    build: ./php
