<?php if ( ! defined("BASEPATH")) exit("No direct script access allowed");

$config['roles'] = array('master','admin','users');

$config['permission'] = array(
'roles' => array( 
'index' => array('master','users'),
'add' => array('master','users'),
'edit' => array('master','users'),
'delete' => array('master','users'),
'delete_all' => array('master','users'),
'manage' => array('master','users'),
'export' => array('master','users'),
'print' => array('master','users'),
'activate' => array('master','users'),
),
'static_seo_pages' => array( 
'index' => array('admin','master','users'),
'add' => array('admin','master','users'),
'edit' => array('admin','master','users'),
'delete' => array('admin','master','users'),
'delete_all' => array('admin','master','users'),
'manage' => array('admin','master','users'),
'export' => array('admin','master','users'),
'print' => array('admin','master','users'),
'activate' => array('admin','master','users'),
),
'images' => array( 
'index' => array('admin','master','users'),
'add' => array('master','users','admin'),
'edit' => array('admin','master','users'),
'delete' => array('master','users','admin'),
'delete_all' => array('master','users','admin'),
'manage' => array('admin','master','users'),
'export' => array('master','users','admin'),
'print' => array('master','users','admin'),
'activate' => array('master','users'),
),
'users' => array( 
'index' => array('master','users','admin'),
'add' => array('master','users','admin'),
'edit' => array('master','users','admin'),
'delete' => array('master','users','admin'),
'delete_all' => array('master','users','admin'),
'manage' => array('master','users','admin'),
'export' => array('master','users','admin'),
'print' => array('master','users','admin'),
'activate' => array('master','users','admin'),
),
'pages' => array( 
'index' => array('admin','master','users'),
'add' => array('master','users'),
'edit' => array('admin','master','users'),
'delete' => array('master','users'),
'delete_all' => array('master','users'),
'manage' => array('admin','master','users'),
'export' => array('master','users'),
'print' => array('master','users'),
'activate' => array('master','users'),
),
'recycle' => array( 
'index' => array('master','users'),
'add' => array('master','users'),
'edit' => array('master','users'),
'delete' => array('master','users'),
'delete_all' => array('master','users'),
'manage' => array('master','users'),
'export' => array('master','users'),
'print' => array('master','users'),
'activate' => array('master','users'),
),
'routes' => array( 
'index' => array('master','admin'),
'add' => array('master','admin'),
'edit' => array('master','admin'),
'delete' => array('master','admin'),
'delete_all' => array('master','admin'),
'manage' => array('master','admin'),
'export' => array('master','admin'),
'print' => array('master','admin'),
'activate' => array('master','admin'),
),
'auto_reply_messages' => array( 
'index' => array('admin','master'),
'add' => array('master'),
'edit' => array('admin','master'),
'delete' => array('master'),
'delete_all' => array('master'),
'manage' => array('admin','master'),
'export' => array('master'),
'print' => array('master'),
'activate' => array('master'),
),
'languages' => array( 
'index' => array('master'),
'add' => array('master'),
'edit' => array('master'),
'delete' => array('master'),
'delete_all' => array('master'),
'manage' => array('master'),
'export' => array('master'),
'print' => array('master'),
'activate' => array('master'),
),
'dynamic_pages' => array( 
'index' => array('admin','master'),
'add' => array('master'),
'edit' => array('admin','master'),
'delete' => array('master'),
'delete_all' => array('master'),
'manage' => array('master'),
'export' => array('master'),
'print' => array('master'),
'activate' => array('master'),
),
'countries' => array( 
'index' => array('master'),
'add' => array('master'),
'edit' => array('master'),
'delete' => array('master'),
'delete_all' => array('master'),
'manage' => array('master'),
'export' => array('master'),
'print' => array('master'),
'activate' => array('master'),
),
'static_translations' => array( 
'index' => array('master'),
'add' => array('master'),
'edit' => array('master'),
'delete' => array('master'),
'delete_all' => array('master'),
'manage' => array('master'),
'export' => array('master'),
'print' => array('master'),
'activate' => array('master'),
),
'our_value' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'our_clients' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'news' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'blog' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'faq' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'fleet' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'category' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'pickup_location' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'dropoff_location' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'bookings' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'blog_category' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'blog_tags' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
'services' => array( 
'index' => array('admin','master'),
'add' => array('admin','master'),
'edit' => array('admin','master'),
'delete' => array('admin','master'),
'delete_all' => array('admin','master'),
'manage' => array('admin','master'),
'export' => array('admin','master'),
'print' => array('admin','master'),
'activate' => array('admin','master'),
),
);
?>