<?php 
$firstname = $_POST['firstname'] ?? '';
$lastname = $_POST['lastname'] ?? '';

$files = $_POST['files'];



?>
<!doctype html>
<html lang="en" >

<head ><title></title>
</head>

<body>

<table align="center" border="0" cellspacing="0" cellpadding="0" width="100%" bgcolor="#EDF0F3" style="background-color:#edf0f3;table-layout:fixed">
<tbody>
<tr>
<td align="center">
<center style="width:100%">
<table border="0" class="m_-7201562315967110282phoenix-email-container" cellspacing="0" cellpadding="0" width="512" bgcolor="#FFFFFF" style="background-color:#ffffff;margin:0 auto;max-width:512px;width:inherit">
<tbody>
<tr>
<td bgcolor="#F6F8FA" style="background-color:#f6f8fa;padding:5px 16px 13px;border-bottom:1px solid #ececec">
   <table border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%!important;min-width:100%!important">
      <tbody>
         <tr>
            <td align="left" valign="middle"><a href="" style="color:#008cc9;display:inline-block;text-decoration:none" target="_blank" data-saferedirecturl=""> 




            	<img alt="DonerandGyros" border="0" src="https://www.donerandgyros.com/front_assets/images/logo.png" height="42" style="outline:none;color:#ffffff;text-decoration:none" class="CToWUd"></a></td>
            <td valign="middle" width="100%" align="right" style="padding:0 0 0 10px;padding-top:7px"><a href="" style="margin:0;color:#008cc9;display:inline-block;text-decoration:none" target="_blank" data-saferedirecturl=""> <span style="word-wrap:break-word;color:#4c4c4c;word-break:break-word;font-weight:400;font-size:14px;line-height:1.429">

            <?= $firstname. ' '.$lastname;?>

         </span></a></td>
            <td valign="middle" width="40" style="padding-top:7px;padding-left:10px"> <a href="" style="border-radius:50%;color:#008cc9;display:inline-block;text-decoration:none" target="_blank" data-saferedirecturl="" style="border-radius:50%;outline:none;color:#ffffff;text-decoration:none" class="CToWUd"></a></td>
            <td width="1">&nbsp;</td>
         </tr>
      </tbody>
   </table>
</td>
</tr>
<tr>
<td>
   <table border="0" cellspacing="0" cellpadding="0" width="100%">
      <tbody>
         <tr>
            <td>
               <table border="0" cellspacing="0" cellpadding="0" width="100%">
                  <tbody>
                     <tr>
                        <td style="padding:24px 24px 36px 24px">
                           <table border="0" cellspacing="0" cellpadding="0" width="100%">
                              <tbody>
                                 <tr>
                                    <td align="left" id="m_-7201562315967110282qatest-hero-headline" colspan="2" style="padding-bottom:12px">
                                       <p style="margin:0;word-wrap:break-word;color:#4c4c4c;word-break:break-word;font-weight:400;font-size:16px;line-height:1.5">Hi,<br> You have got assignments from administrator.</p>
                                    </td>


                                 </tr>

                                 <tr>
                                  


                                 </tr>


                                 <tr>
                                    <td valign="top" width="70" style="width:70px">
                                       <table border="0" cellspacing="0" cellpadding="0" width="100%">
                                          

                                       </table>
                                    </td>
                                    <td style="padding-top:5px">
                                     
                                    </td>
                                 </tr>
                              </tbody>
                           </table>

                           

                           
                           <br/>

                           <?php if(count($files) > 0) :?>

                           <?php foreach($files as $key => $value) :?>

                              <table border="0" cellspacing="0" cellpadding="0" width="auto"> <tbody> <tr> <td style="border-radius:2px;padding:6px 16px;color:#4c4c4c;font-weight:500;font-size:16px;border-color:#737373;border-width:1px;border-style:solid">



                              <a href="<?= $value;?>" style="color:#4c4c4c;display:inline-block;text-decoration:none" target="_blank" data-saferedirecturl="" download>Download</a>




                           </td> </tr> </tbody> </table>

                           <br/>

                           <?php endforeach ;?>

                           <?php endif; ?>
                           

                           <br/>

                           <table border="0" cellspacing="0" cellpadding="0" width="auto"> <tbody> <tr> <td style="border-radius:2px;padding:6px 16px;color:#4c4c4c;font-weight:500;font-size:16px;">


                              Thank You.




                           </td> </tr> </tbody> </table>

                        </td>
                     </tr>
                  </tbody>
               </table>
               <div>
                  <div>   </div>
                  <div>   </div>
               </div>
            </td>
         </tr>
      </tbody>
   </table>
</td>
</tr>
<tr>
<td>
   <table border="0" cellspacing="0" cellpadding="0" width="100%" bgcolor="#EDF0F3" align="center" style="background-color:#edf0f3;padding:0 24px;color:#6a6c6d;text-align:center">
      <tbody>
         <tr>
            <td align="center" style="padding:16px 0 0 0;text-align:center">
               <table align="center" border="0" cellspacing="0" cellpadding="0" width="100%">
                  <tbody>
                     <tr>
                        <td valign="middle" align="center" style="padding:0 0 16px 0;vertical-align:middle;text-align:center"><a href="" style="color:#6a6c6d;text-decoration:underline;display:inline-block" target="_blank" data-saferedirecturl=""> <span style="color:#6a6c6d;font-weight:400;text-decoration:underline;font-size:12px;line-height:1.333">Unsubscribe</span></a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="" style="color:#6a6c6d;text-decoration:underline;display:inline-block" target="_blank" data-saferedirecturl=""> <span style="color:#6a6c6d;font-weight:400;text-decoration:underline;font-size:12px;line-height:1.333">Help</span></a></td>
                     </tr>
                  </tbody>
               </table>
            </td>
         </tr>
         <tr>
            <td>
               <table border="0" cellspacing="0" cellpadding="0" width="100%">
                  <tbody>
                     <tr>
                        <td align="center" style="padding:0 0 12px 0;text-align:center">
                           <p style="margin:0;color:#6a6c6d;font-weight:400;font-size:12px;line-height:1.333">You are receiving Invitation emails.</p>
                        </td>
                     </tr>
                    
                     <tr>
                        <td align="center" style="padding:0 0 8px 0;text-align:center"><a href="" style="color:#6a6c6d;text-decoration:underline;display:inline-block" target="_blank" data-saferedirecturl="">


                        	<img alt="LinkedIn" border="0" height="14" src="https://www.donerandgyros.com/front_assets/images/logo.png" width="58" style="outline:none;color:#ffffff;display:block;text-decoration:none" class="CToWUd"></a></td>
                     </tr>
                     <tr>
                        <td align="center" style="padding:0 0 12px 0;text-align:center">
                           <p style="margin:0;color:#6a6c6d;font-weight:400;font-size:12px;line-height:1.333">© Office#1202, Saba Tower 1, Cluster E,
Jumeirah Lake Towers, Dubai-UAE</p>
                        </td>
                     </tr>
                  </tbody>
               </table>
            </td>
         </tr>
      </tbody>
   </table>
</td>
</tr>
</tbody>
</table>
</center>
</td>
</tr>
</tbody>
</table>
</body>
</html>